### ISSUE TITLE
panic in ci-tools/pkg/results/report.go

### ISSUE THREAD

**Issue by miabbott** [openshift/ci-tools#692]
Observed the following panic in a job kicked off by `cluster-bot` - https://storage.googleapis.com/origin-ci-test/logs/release-openshift-origin-installer-e2e-gcp-upgrade/673/build-log.txt

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x1704aee]

goroutine 1 [running]:
github.com/openshift/ci-tools/pkg/results.(*reporter).Report(0xc000e815c0, 0x1e85480, 0xc000620690)
	/go/src/github.com/openshift/ci-tools/pkg/results/report.go:144 +0x2fe
main.(*options).Report(0xc0002062c0, 0x1e83ec0, 0xc000620690)
	/go/src/github.com/openshift/ci-tools/cmd/ci-operator/main.go:504 +0xf7
main.main()
	/go/src/github.com/openshift/ci-tools/cmd/ci-operator/main.go:201 +0x30e
```

**Comment by alvaroaleman** [comment]
Fixed in https://github.com/openshift/ci-tools/pull/693
/close
